name: ci-pipeline

on:
  push:
    branches: ["main"]

jobs: 
  builds:
      run-on: ubuntu-latest

      env: 
        NODE-ENV: production
        API-KEY: ${{secrets.API_KEY}} 

      steps: 
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js 
          uses: actions/setup-node@v3 
          with: 
            nod-version: '20' 
        
        - name: Install dependencies
          run: npm install 

        - name: Run tests 
          run: npm test 
        
        - name: Build app
          run: npm run build
        
        - name: Deploy app 
          run: npm run deploy
          
